apiVersion: v1
kind: Secret
metadata:
  namespace: opensearch
  name: internalusers
type: Opaque
stringData:
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2a$12$cmc4YOCkrVdtfhMBgJusAeVFcdrq8cgUY7V0VxtiHLwqM2bulXx6i"
      reserved: true
      backend_roles:
        - "admin"
      description: "Demo admin user"
    dashboarduser:
      hash: "$2a$12$cmc4YOCkrVdtfhMBgJusAeVFcdrq8cgUY7V0VxtiHLwqM2bulXx6i"
      reserved: true
      description: "Demo OpenSearch Dashboards user"
