grafana:
  plugins:
    - grafana-clickhouse-datasource

  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
    plugins:
      enabled: true
    alerts:
      enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "ca-issuer"
    path: /
    pathType: Prefix
    hosts:
      - grafana.k8s.local
    tls:
      - hosts:    
          - grafana.k8s.local    
        secretName: grafana-cert
