toolbox:
  enabled: true
  resources:
    limits:
      cpu: "128M"
      memory: "256Mi"

cephClusterSpec:
  mon:
    count: 1
  mgr:
    count: 1
  crashCollector:
    disable: true
  logCollector:
    enabled: false
  resources:
    mgr:
      limits:
        cpu: "512m"
        memory: "512Mi"
      requests:
        cpu: "256m"
        memory: "256Mi"
    mon:
      limits:
        cpu: "512m"
        memory: "512Mi"
      requests:
        cpu: "256m"
        memory: "256Mi"
    osd:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "256m"
        memory: "512Mi"

dashbard:
  enabled: true
  ssl: false

configOverride: |
  [global]
  osd_pool_default_size = 1
  mon_warn_on_pool_no_redundancy = false
  bdev_flock_retry = 20
  bluefs_buffered_io = false
  mon_data_avail_warn = 10

ingress:
  dashboard:
    annotations:
      cert-manager.io/cluster-issuer: "ca-issuer"
    host:
      name: rook.k8s.local
      pathPrefix: "/ceph-dashboard(/|$)(.*)"
    tls:
    - hosts:
        - rook.k8s.local
      secretName: rook-cert
    ingressClassName: traefik

