apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-cluster
  namespace: clickhouse
spec:
  #disable public loadbalancer
  defaults:
    templates:
      serviceTemplate: service-nolb


  configuration:
    clusters:
      - name: clickhouse
        templates:
          podTemplate: server

    # create the admin user that can access from anywhere
    users:
      admin/networks/ip: 
        - "0.0.0.0/0"
        - "::/0"
      admin/password: adminpwd
      admin/profile: default
      admin/quota: default
      grafana/networks/ip:
        - "0.0.0.0/0"
        - "::/0"
      grafana/password: grafanapwd
      grafana/profile: readonly
      grafana/quota: default
    profiles:
      readonly/readonly: 1

    # set log to INFO
    settings:
      logger/level: information

  templates:
      serviceTemplates:
        - name: service-nolb
          generateName: "clickhouse-{chi}"
          spec:
            ports:
              - name: http
                port: 8123
              - name: tcp
                port: 9000
              - name: interserver
                port: 9009
            type: ClusterIP
            ClusterIP: None

      podTemplates:
        - name: server
          spec:
            containers:
              - name: clickhouse
                image: clickhouse/clickhouse-server:latest
                volumeMounts:
                  - name: data-storage-template
                    mountPath: /var/lib/clickhouse

      volumeClaimTemplates:
        - name: data-storage-template
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi





