# This is how we can handle main UI https redirect to the internal console service http
# The error is:
# """ Mixed Content: The page at 'https://keycloak.k8s.local/admin/master/console/' was loaded over HTTPS, 
# but requested an insecure resource 'http://keycloak.k8s.local/realms/master/protocol/openid-connect/3p-cookies/step1.html'.
# This request has been blocked; the content must be served over HTTPS.""""
proxy: edge

# Helm delete doesn't delete the old pvc which holds postgresql data 
# so we need to specify the password for nb_keycloak (psotgres) user to have the same password always
postgresql:
  password: keycloakpwd

# Usual ingress definition
ingress:
  tls: true
  enabled: true
  ingressClassName: traefik
  hostname: keycloak.k8s.local
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
    



