
providers:
  kubernetesCRD:
    allowExternalNameServices: true

ingressRoute:    
  dashboard:    
    enabled: true
    entryPoints: ["web","websecure"]    
    matchRule: Host(`traefik.k8s.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))

