{
 "title": "ClickHouse k8s Logs",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Nodes",
    "query": "select distinct(ResourceAttributes['k8s.node.name']) as node from otel.otel_logs where ResourceAttributes['k8s.node.name']!=''; "
   },
   {
    "name": "namespace",
    "label": "Namespaces",
    "query": "select distinct(ResourceAttributes['k8s.namespace.name']) as namespace from otel.otel_logs where namespace!='' and ResourceAttributes['k8s.node.name'] in (${node})"
   },
   {
    "name": "pod",
    "label": "Pods",
    "query": "select distinct(ResourceAttributes['k8s.pod.name']) as pod from otel.otel_logs where ResourceAttributes['k8s.node.name'] in (${node}) and ResourceAttributes['k8s.namespace.name'] in (${namespace})"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(ResourceAttributes['k8s.node.name'])) as node from otel.otel_logs where ResourceAttributes['k8s.node.name']!='' and $__timeFilter(Timestamp)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Number of namespaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(ResourceAttributes['k8s.namespace.name'])) as node from otel.otel_logs where $__timeFilter(Timestamp)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(ResourceAttributes['k8s.pod.name'])) as node from otel.otel_logs where $__timeFilter(Timestamp)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Number of containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(ResourceAttributes['k8s.container.name'])) as node from otel.otel_logs where $__timeFilter(Timestamp)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Log levels",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  If(\n     extractKeyValuePairs(Body,'=')['level'] == '', 'unknown',  extractKeyValuePairs(Body,'=')['level']\n  ) as level,\n  count(level) as count  \nfrom otel.otel_logs\nwhere $__timeFilter(Timestamp)\nand ResourceAttributes['k8s.node.name'] in (${node}) and  ResourceAttributes['k8s.pod.name'] in (${pod})\ngroup by level;\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Log iostreams",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select LogAttributes['log.iostream'] as stream,\n  count(stream) as count  \nfrom otel.otel_logs\nwhere $__timeFilter(Timestamp)\nand ResourceAttributes['k8s.node.name'] in (${node}) and  ResourceAttributes['k8s.pod.name'] in (${pod})\ngroup by stream;\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Log freguency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT toDateTime(toStartOfInterval(Timestamp, INTERVAL 60 second)) as time, SeverityText, count() as count\nFROM otel.otel_logs\nWHERE $__timeFilter(time)\nand ResourceAttributes['k8s.node.name'] in (${node}) and  ResourceAttributes['k8s.pod.name'] in (${pod})\nGROUP BY SeverityText, time\nORDER BY time;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Logs per Node",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ResourceAttributes['k8s.node.name'] AS node, count(*) AS count \nFROM otel.otel_logs\nWHERE ResourceAttributes['k8s.node.name'] IN (${node}) \nAND $__timeFilter(Timestamp)\nGROUP BY ResourceAttributes['k8s.node.name']",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Logs per Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select ResourceAttributes['k8s.pod.name'] as pod, count(*) as count \nfrom otel.otel_logs \nwhere ResourceAttributes['k8s.node.name'] in (${node}) and  ResourceAttributes['k8s.pod.name'] in (${pod})\nand $__timeFilter(Timestamp)\ngroup by ResourceAttributes['k8s.pod.name']",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Last 100 logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT  Timestamp, Body, ResourceAttributes, LogAttributes \nFROM  otel.otel_logs \nwhere ResourceAttributes['k8s.node.name'] in (${node}) \nand  ResourceAttributes['k8s.pod.name'] in (${pod}) \nand $__timeFilter(Timestamp)\norder by Timestamp desc\nlimit 100",
     "selectedFormat": 4
    }
   ]
  }
 ]
}