apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-monitor
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  project: k8s-lab
  source:
    path: custom-apps/argocd-servicemonitor
    repoURL: 'https://gitlab.com/talentiaacademy/k8s-helm-training.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
