apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator
  namespace: argocd
spec:
  destination:
    namespace: clickhouse
    server: 'https://kubernetes.default.svc'
  project: k8s-lab
  source:
    path: custom-apps/clickhouse-operator/helm
    repoURL: 'https://gitlab.com/talentiaacademy/k8s-helm-training.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
