apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collectors
  namespace: argocd
spec:
  destination:
    namespace: opentelemetry
    server: https://kubernetes.default.svc
  project: k8s-lab
  source:
    path: custom-apps/opentelemetry-operator/collectors
    repoURL: https://gitlab.com/talentiaacademy/k8s-helm-training.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
