apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  destination:
    namespace: opentelemetry
    server: https://kubernetes.default.svc
  project: k8s-lab
  source:
    path: custom-apps/opentelemetry-operator
    repoURL: https://gitlab.com/talentiaacademy/k8s-helm-training.git
    targetRevision: HEAD
    directory:
      recurse: true
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
