apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  project: k8s-lab
  source:
    path: custom-apps/prometheus-operator/helm
    repoURL: 'https://gitlab.com/talentiaacademy/k8s-training.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true # this needs because of the long annotations in the CRD definitions; prometheus is a shit

