apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-logstash
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
  - host: logstash.k8s.local
    http:
      paths:
      - backend:
          service:
            name: logstash-logstash
            port:
              number: 5044
        path: /
        pathType: Prefix
