image: "milkfinch/logstash-oss"
imageTag: "8.5.0-loki"

persistence:
  enabled: false

logstashConfig:
  logstash.yml: |
    log.level: info
    api.http.host: 0.0.0.0

logstashPipeline:
  logstash.conf: |
    input { beats { port => 5044 } }
    filter {
        if [kubernetes] {
          mutate {
            add_field => {
              "container_name" => "%{[kubernetes][container][name]}"
              "namespace" => "%{[kubernetes][namespace]}"
              "pod" => "%{[kubernetes][pod][name]}"
            }
            replace => { "host" => "%{[kubernetes][node][name]}"}
          }
        }
        mutate {
          remove_field => ["tags"]
        }
    }
    output {
        loki {
            url => "http://loki.k8s.local/loki/api/v1/push"
        }
    }

service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044


