operator:
  replicaCount: 1

console:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "ca-issuer"
    host: minio-operator.k8s.local
    path: /console
    pathType: Prefix
    tls:
      - hosts:    
          - minio-operator.k8s.local    
        secretName: minio-operator-cert